### PR TITLE
Onyx Bump 2.0.47: `null` -> `undefined` changes

### PR DESCRIPTION
**Pull request by chrispader**
@mountiny 

### Details

~Requires https://github.com/Expensify/react-native-onyx/pull/556 to get merged first!~

Requires https://github.com/Expensify/react-native-onyx/pull/558 to get merged first

Part of the Onyx bump to 2.0.43 in https://github.com/Expensify/App/pull/42772

This PR applies all the changes needed to work with Onyx version `2.0.43`. This will be mostly changing types, default values and null-handling for output by Onyx.

### Fixed Issues

$
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

### CODE REVIEW

**Comment by chrispader** [comment]
@mountiny this should be ready for review! can we trigger QA on this?

(Note that i had to create the PR in our `margelo` E/App fork, because both branches or on this fork

**Comment by chrispader** [comment]
> can we trigger QA on this?

If not, i can create a combined PR, with all the changes (also from the base branch) so we can trigger QA, but still review separately

**Comment by s77rt** [comment]
Looks we have some unrelated commits, can you clean those up?

**Comment by chrispader** [comment]
> Looks we have some unrelated commits, can you clean those up?

@s77rt done! :)

**Comment by s77rt** [comment]
Report screen empty

https://github.com/margelo/expensify-app-fork/assets/16493223/0e43a400-7c82-4295-9f60-4c897fbb8dd6

**Comment by s77rt** [comment]
On first render the header is missing

https://github.com/margelo/expensify-app-fork/assets/16493223/99e0cadc-8dc1-4ff3-9ae6-e8a053f8181e

**Comment by s77rt** [comment]
First time submitting an expense getting an empty view

https://github.com/margelo/expensify-app-fork/assets/16493223/df6daa6f-a47c-4228-b1f3-57b73f89f84a

**Comment by s77rt** [comment]
Emoji suggestion not working

https://github.com/margelo/expensify-app-fork/assets/16493223/adee3eb2-5835-43d1-9ebd-911f9b0fc7b5

**Comment by s77rt** [comment]
Infinite loader on attachments and not loading in chats

https://github.com/margelo/expensify-app-fork/assets/16493223/9da68ebc-017a-4e50-943d-53540b88b97e

**Comment by chrispader** [comment]
Fixing these issues in https://github.com/Expensify/react-native-onyx/pull/558

**Comment by chrispader** [comment]
> First time submitting an expense getting an empty view

Also fixed by the same change in https://github.com/Expensify/react-native-onyx/pull/558

**Comment by chrispader** [comment]
> Emoji suggestion not working

fixed!

**Comment by s77rt** [comment]
Empty report on refresh

https://github.com/margelo/expensify-app-fork/assets/16493223/e02f91d8-6565-4a0a-89ec-d016455e28a5

**Comment by s77rt** [comment]
Do we need to wait for https://github.com/Expensify/react-native-onyx/pull/558?

**Comment by chrispader** [comment]
> Do we need to wait for [Expensify/react-native-onyx#558](https://github.com/Expensify/react-native-onyx/pull/558)?

Yes, you continue doing QA on this PR, but please check out the changes from https://github.com/Expensify/react-native-onyx/pull/558? in `react-native-onyx` and link them locally.

You can do so, by running `npm run build:watch` in Onyx and run `npx link publish <path_to_onyx>` once in E/App

**Comment by chrispader** [comment]
Also, once you applied the new changes from Onyx, please make sure to logout from E/App once, since some changes will only apply after the DB was cleared on log-out

**Comment by s77rt** [comment]
After applying the onyx changes I'm not able to login (no request is sent to the server)


https://github.com/margelo/expensify-app-fork/assets/16493223/34766205-e770-421d-80bf-6f8d1a9ef76c

**Comment by ikevin127** [comment]
@s77rt I just applied the new onyx changes too, I think the login issue is due to some recently reported performance issue on BE side, see [incident](https://status.expensify.com/incidents/3rtn5n537q6b) and more details on https://status.expensify.com.

> [!note]
> I'm also awaiting the performance issues to be solved so I can continue testing.

**Comment by s77rt** [comment]
The login bug is a FE bug. The `NetworkStore.hasReadRequiredDataFromStorage()` promise is never resolved 

https://github.com/margelo/expensify-app-fork/blob/a04f40e09e6a933488957b7f6300edd6290c1ebd/src/libs/Network/NetworkStore.ts#L33-L43

**Comment by s77rt** [comment]
After onyx changes the report screen is empty all the time

https://github.com/margelo/expensify-app-fork/assets/16493223/d90389b4-6577-41ca-9e74-55d4b50ebd97

**Comment by s77rt** [comment]
> > First time submitting an expense getting an empty view
> 
> Also fixed by the same change in [Expensify/react-native-onyx#558](https://github.com/Expensify/react-native-onyx/pull/558)

I can still reproduce this one

**Comment by ikevin127** [comment]
I commented out the early return mentioned in https://github.com/margelo/expensify-app-fork/pull/20#issuecomment-2148589255 in order to be able to login.

> After onyx changes the report screen is empty all the time

This is not reproducible on my side:

https://github.com/margelo/expensify-app-fork/assets/56457735/568c8cfd-a1f4-4a7a-9162-13b4773319a0

The only thing I did differently (probably) is that when I was logged-out I cleared all the keys in onyx indexed db, then performed login as mentioned above.

##

Continuing testing...

**Comment by ikevin127** [comment]
Re-tested previously triaged ⚠️ issues from https://github.com/Expensify/App/pull/42057#issuecomment-2118617952:

✅ [Web - Chat - URL is not hyperlinked on chat composer](https://github.com/Expensify/App/pull/42057#issuecomment-2110377382)

Still fixed, not reproducible!

⚠️ [Web - Receipt - Delete receipt is not displayed](https://github.com/Expensify/App/pull/42057#issuecomment-2110474366)

While the `Delete receipt` button **does** show-up, the issue now is that after the date is changed (step 9.), revisiting the receipt attachment modal now shows page not found:

<details>
<summary>Video</summary>

https://github.com/margelo/expensify-app-fork/assets/56457735/72bf86eb-9661-44b4-87f9-fc807c82cc5c

</details>

✅ [Web - Receipt - Its not here page is displayed when trying to replace a receipt](https://github.com/Expensify/App/pull/42057#issuecomment-2110493936)

Still fixed, with the **mention** that given the same steps as above, when revisiting the receipt we still see the page not found in the attachment modal. But the `Replace` receipt works correctly, opening the RHP with the upload receipt UI.

✅ [Web - Distance - Distance receipt only shows the map](https://github.com/Expensify/App/pull/42057#issuecomment-2110548378)

Still fixed, not reproducible!

✅ [Category - Keyboard navigation in category list is blocked when there is Recent section](https://github.com/Expensify/App/pull/42057#issuecomment-2111103644)

Still fixed, not reproducible!
**Note:** Fixed by commit https://github.com/Expensify/App/pull/42057/commits/e7e73c8e1c5fea51fc7d5d626afe066b007325c1.

## 

cc @chrispader @mountiny 

Tomorrow I'll continue working on the 2nd action mentioned in [Slack 🧵](https://expensify.slack.com/archives/C05R2V5GM1S/p1717193187147939):
> 2. Dive into the code and take note of the components where `null -> undefined` change was made and check the parts of the app where these components live in order to test for bugs.

**Comment by chrispader** [comment]
@s77rt are you sure you checked-out the changes from https://github.com/Expensify/react-native-onyx/pull/558 and they are linked correctly locally?

I'm pretty sure these issues should be fixed with the latest Onyx changes and @ikevin127 seems to not repro them either

**Comment by chrispader** [comment]
> @s77rt I just applied the new onyx changes too, I think the login issue is due to some recently reported performance issue on BE side, see [incident](https://status.expensify.com/incidents/3rtn5n537q6b) and more details on https://status.expensify.com.
>
> > After applying the onyx changes I'm not able to login (no request is sent to the server)
> 
> I can confirm this as well, I even cleared the onyx storage completely and sometimes I get the `Another login page is open.` instead of the login input field:

Fixed!

**Comment by chrispader** [comment]
@s77rt i fixed the login issue, but i cannot reproduce the rest of your reported issues.

Are you sure you checked out the Onyx changes from https://github.com/Expensify/react-native-onyx/pull/558 and linked them locally using `npx link publish <path_to_onyx>`?

**Comment by chrispader** [comment]
@ikevin127 @s77rt the changes from https://github.com/Expensify/react-native-onyx/pull/558 should only be applied to this specific PR btw.

https://github.com/Expensify/App/pull/42772 can be tested as-is.

**Comment by s77rt** [comment]
@chrispader I'm still facing same issue. For onyx I have switched to the `@chrispader/fix-onyx-bump-fixes` branch and linked correctly. I have also added a console log to verify I'm using the local onyx.




https://github.com/margelo/expensify-app-fork/assets/16493223/b98a0c44-e472-4c22-a4db-735ef7cd2f5e

**Comment by chrispader** [comment]
> @s77rt Try logging out, deleting all keys in Inspect > Application > IndexedDB > OnyxDB > keyvaluepairs and refresh the login page after doing that. Now login normally and you should not get the empty report screens anymore (that's what worked for me).

@ikevin127 @s77rt i just changed a lot of parts of the app and this (☝🏼) is actually what fixes a lot of issues. For me, everything works fine now. Please continue with QA and let me know if there are any other issues.

When we deploy this Bump PR, it would probably be best to force a sign-out for all users and clear the database, because a lot of data might be stale (`null` values in storage instead of `undefined`) which might cause problems.

**Comment by ikevin127** [comment]
## ✅ Issues reported by other testers and triaged as fixed:

* [x] [On first render the header is missing](https://github.com/margelo/expensify-app-fork/pull/20#issuecomment-2143117116)
* [x] [First time submitting an expense getting an empty view](https://github.com/margelo/expensify-app-fork/pull/20#issuecomment-2143118198)
* [x] [Emoji suggestion not working](https://github.com/margelo/expensify-app-fork/pull/20#issuecomment-2143121187)
* [x] [Infinite loader on attachments and not loading in chats](https://github.com/margelo/expensify-app-fork/pull/20#issuecomment-2143130764)
* [x] [Empty report on refresh](https://github.com/margelo/expensify-app-fork/pull/20#issuecomment-2148377216)
* [x] [Not able to login (no request is sent to the server)](https://github.com/margelo/expensify-app-fork/pull/20#issuecomment-2148570767)

## ⚠️ Issues found **today** during overall app testing:

> [!important]
> **All these were cross-tested on latest staging (v1.4.79-10) where none of them are reproducible.**
> They **only** occur on this PR with the https://github.com/Expensify/react-native-onyx/pull/558 changes applied as per https://github.com/margelo/expensify-app-fork/pull/20#issuecomment-2148402604.

##

1. * [ ] **Nested** `Thread` **back button navigation shows** `Hmm... it's not here` **page**
      
      **Component source:** [ThreadDivider.tsx](https://github.com/Expensify/App/blob/5b56d76b993bc9ca50750070e5f39f324fb20d7a/src/pages/home/report/ThreadDivider.tsx)

      **Steps:**
      1. Navigate to a report and post a message.
      3. Hover over the sent message and press `Reply in thread`.
      4. Post a message within the thread.
      5. Repeat step 2 and 3 such that you have a 3-level nested thread.
      6. Navigate to the 2nd or 3rd level of the thread and press on the Screenshot 2024-06-05 at 17 16 04 button such that you're navigated back out of the nested thread.
      
      **Expected result:** We're navigated back out of the nested thread of which Screenshot 2024-06-05 at 17 16 04 button we pressed.
      **Actual result:** We're shown the `Hmm... it's not here - You don't have access to this chat` report screen.

      <details>
      <summary>Video</summary>
      
      https://github.com/margelo/expensify-app-fork/assets/56457735/8a578a83-b930-431e-b3a6-c3ea71cc9e03
      
      </details>

##
### To be continued...

**Comment by s77rt** [comment]
Tested again and now I'm seeing the report but the header is gone

Screenshot 2024-06-06 at 2 50 20 PM

**Comment by s77rt** [comment]
Can you merge `Onyx:main` into `margelo:@chrispader/fix-onyx-bump-fixes`

**Comment by s77rt** [comment]
The submit expense to a user is still empty in my testing
Screenshot 2024-06-06 at 3 18 15 PM

**Comment by s77rt** [comment]
The split details too
Screenshot 2024-06-06 at 3 20 43 PM

**Comment by s77rt** [comment]
@chrispader That's a great find! Indeed that was the issue!

**Comment by chrispader** [comment]
At the moment it seems all issues with this PR are resolved. @mountiny

@s77rt issues are fixed by the instructions in the last comment

The "Going back on threads" issue reported by @ikevin127 is also reproducible on staging, as in https://github.com/Expensify/App/issues/43172

I'm gonna wait for further testing results from you guys, until then i'm gonna focus on some other tasks.

**Comment by s77rt** [comment]
Been testing this for a while didn't find any bug yet

**Pull request merged**
